name: galletas_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependencias finales y correctas
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  barcode_widget: ^2.0.4
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  csv: ^6.0.0
  share_plus: ^9.0.0
  mobile_scanner: ^5.1.1
  
  # EL PAQUETE CORRECTO
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true